/* eslint-disable */
export const ADD_INVESTMENT = 'ADD_INVESTMENT';
export const REMOVE_INVESTMENT = 'REMOVE_INVESTMENT'
export const UPDATE_INVESTMENT = 'UPDATE_INVESTMENT'
export const SELECT_INVESTMENT = 'SELECT_INVESTMENT'
export const SELECT_INVESTMENT_OPERATION = 'SELECT_INVESTMENT_OPERATION'
export const NEW_INVESTMENT_OPERATION = 'NEW_INVESTMENT_OPERATION'
export const FILTER_INVESTMENT_OPERATIONS = 'FILTER_INVESTMENT_OPERATIONS'
export const INVESTMENT_PROFIT = 'INVESTMENT_PROFIT'
export const LOAD_FROM_DB = 'LOAD_FROM_DB'
export const IMPORT_DB = 'IMPORT_DB'
export const EXPORT_DB = 'EXPORT_DB'
export const REMOVE_DB = 'REMOVE_DB'
